Add course review rejection reason
thinc-org/cugetreg pull request #449
Opened 2022-12-19 15:13 UTC by tithanayut

## Why did you create this PR

-

## What did you do

-

## Demo

[https://dev.cugetreg.com](https://dev.cugetreg.com)

## Checklist

- [ ] Deploy a demo
- [ ] Check browsers compatibility
- [ ] Wrote coverage tests

2022-12-19 16:56 UTC, bombnp requested changes
what the fuck so fast

2022-12-19 16:56 UTC, bombnp commented on apps/api/src/review/review.resolver.ts
> +    @Args('rejectionReason') rejectionReason?: ReviewStatus
shouldn't this be string?

2022-12-19 16:58 UTC, tithanayut commented on apps/api/src/review/review.resolver.ts
> +    @Args('rejectionReason') rejectionReason?: ReviewStatus
oops

2022-12-19 16:58 UTC, tithanayut commented
Because some project cancelled the meeting so I have time!

2022-12-19 17:10 UTC, bombnp commented
I'm trying to get it to work with Appsmith on dev env, but it looks like our CI/CD is DEAD!
![image](https://user-images.githubusercontent.com/24814968/208481278-6c459c40-b565-44bb-bdac-a2475397603e.png)

2022-12-21 18:37 UTC, bombnp commented
@tithanayut can u trigger a deployment of web and api on dev?

2022-12-21 19:09 UTC, tithanayut commented
@bombnp Done

2022-12-22 12:59 UTC, bombnp commented
![image](https://user-images.githubusercontent.com/24814968/209139475-e7160bee-60bc-48ab-9a5d-c331c38975a6.png)
yea it works, good stuff

2022-12-22 13:00 UTC, bombnp approved these changes
I already edited the appsmith to add support for this in [Dev subpage](https://appsmith.internal.cugetreg.com/applications/6155d8914a99086ac822a925/pages/61817189072a84335bf197df). You can try it there.

Nice kub.

2022-12-22 13:05 UTC, merged